##################################################
### KEYBINDINGS
##################################################

bind = ALT, W, exec, ~/scripts/wallpaper-switcher.sh 
bind = ALT, P, exec, ~/scripts/power-menu.sh

#Screenshot
bind = $mainMod, PRINT, exec, hyprshot -m window
bind = , PRINT, exec, hyprshot -m output 
bind = SUPER_SHIFT, PRINT, exec, hyprshot -m region 
bind = ALT, up, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bind = ALT, down, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = ALT, left, exec, brightnessctl -e4 -n2 set 5%-
bind = ALT, right, exec, brightnessctl -e4 -n2 set 5%+
