general {
    gaps_in = 6
    gaps_out = 10
    border_size = 1
    col.active_border = $foregroundCol
    col.inactive_border = $color1
    resize_on_border = false
    allow_tearing = false
    layout = master
}

master {
    new_status = slave
    mfact = 0.45
    orientation = left
}

bind = SUPER, Return, layoutmsg, swapwithmaster
bind = SUPER, j, layoutmsg, cyclenext
bind = SUPER, k, layoutmsg, cycleprev
bind = SUPER, h, layoutmsg, mfact -0.05
bind = SUPER, l, layoutmsg, mfact +0.05
