#!/usr/bin/env bash
set -euo pipefail

WALL="$1"

# sanity
if [ -z "$WALL" ] || [ ! -f "$WALL" ]; then
  echo "Usage: $0 /path/to/wallpaper.jpg" >&2
  exit 2
fi

LOCK_WALL="$HOME/.cache/current_wallpaper"

# Copy wallpaper for hyprlock (use cp, not ln, for safety)
cp -f "$WALL" "$LOCK_WALL"


# 1) Set wallpaper (swww)
if command -v swww >/dev/null 2>&1; then
  swww img "$WALL" --transition-step 90 --transition-fps 60 --transition-type grow || true
fi

# 2) Generate colors with pywal
if command -v wal >/dev/null 2>&1; then
  wal --cols16 -i "$WALL" -n
else
  echo "pywal (wal) not found" >&2
fi

# Wait a tiny bit for files to appear
sleep 0.12

# 3) Build a safe Hyprland color file (no hashes, uppercase/lowercase ok)
CACHE_COLORS="$HOME/.cache/wal/colors"
HYPR_COL_FILE="$HOME/.config/hypr/wal-hypr.conf"

if [ ! -f "$CACHE_COLORS" ]; then
  echo "Error: $CACHE_COLORS not found" >&2
  exit 3
fi

# Function to read nth line and sanitize
getcolor() {
  local n="$1"
  sed -n "${n}p" "$CACHE_COLORS" 2>/dev/null | tr -d '\r\n' | sed 's/^#//; s/ //g'
}

cat > "$HYPR_COL_FILE" <<EOF
# Auto-generated by setwall.sh
\$color0 = rgb(#$(getcolor 1))
\$color1 = rgb(#$(getcolor 2))
\$color2 = rgb(#$(getcolor 3))
\$color3 = rgb(#$(getcolor 4))
\$color4 = rgb(#$(getcolor 5))
\$color5 = rgb(#$(getcolor 6))
\$color6 = rgb(#$(getcolor 7))
\$color7 = rgb(#$(getcolor 8))
EOF

# 4) Try to reload Waybar / kitty / hyprland
# Waybar
if pgrep -x waybar >/dev/null 2>&1; then
  pkill -SIGUSR2 waybar || true
fi

# Kitty (only if remote control enabled)
if command -v kitty >/dev/null 2>&1; then
  kitty @ set-colors --all ~/.cache/wal/colors-kitty.conf 2>/dev/null || true
fi

# Hyprland reload
if command -v hyprctl >/dev/null 2>&1; then
  hyprctl reload || true
fi

echo "setwall: done. Hyprland colors written to $HYPR_COL_FILE"

